### ISSUE TITLE
Correct docs for app-delivery & improve usability

### ISSUE THREAD

**Issue by skinny85** [awslabs/aws-cdk#1151]
1. (Found by @moofish32 on Gitter) This is wrong:

```ts
const project = new codebuild.PipelineProject(pipelineStack, 'CodeBuild', {
  /* ... */
});
const synthesizedApp = project.outputArtifact;
```

`Project` doesn't have an `outputArtifact` property, it's a CodePipeline thing. It's also missing a build Pipeline Stage.

So, it should be something like:

```ts
const project = new codebuild.PipelineProject(pipelineStack, 'CodeBuild', {
  /* ... */
});
const buildStage = pipeline.addStage('build');
const buildAction = project.addBuildToPipeline(buildStage, 'CodeBuild');
const synthesizedApp = buildAction.outputArtifact;
```

2. It uses `import cicd = require('@aws-cdk/cicd');`, which doesn't exist anymore (the name was changed).

**Comment by RomainMuller** [comment]
Über-oops. Thanks for the report! It's probably a good idea to turn this into a literate markdown example if possible (not sure this can be done without incurring dependency cycles, though).

**Comment by moofish32** [comment]
I would like to make this issue a little broader (include the doc update, but also the major missing feature for IAM).

I created a very simple app-delivery [example:](https://gist.github.com/moofish32/30aed42671079e6da215dbac7bda4fb6)

The app is basically a security group that is whitelisting an IP and Port. Think about an old data center stuck application that you need access to in AWS (perhaps it's not even owned by you). This practice of IP whitelisting is a last resort and should generally be avoided, but it's a simple example. 

As the IP addresses change you would like the security group automatically updated, because IPs are either owned by the service or not, the concept of semver doesn't really apply to this use case. So imagine you update the repo and this artifact is put in an S3 bucket which you want to update your security group.

The VPC parameter here presents an interesting challenge for the app-delivery package. If you want to provide this pattern in a common place for all accounts in your organization AWS Service Catalog might a good place to interface. That means that you need to allow the account to parameterize VPC ID and thus now you need to update a stack and do the equivalent of `user previous value`. I am not positive but I assume this lives in the Parameter Overrides.

In order to deploy the security group you will need a base set of permissions passed to the role executing the change set. Today that is the missing feature.

If we really want a separate issue for docs, let me know.

**Comment by moofish32** [comment]
I can't update title or description -- so if we agree to consolidate can somebody with access take care of that?

**Comment by moofish32** [comment]
For other users hitting this issue you can work around using our escape hatch similar too:

```typescript
const pipelineActions: cfn.PipelineCreateReplaceChangeSetAction = deployAction.children.
  find( c => (c as cfn.PipelineCreateReplaceChangeSetAction).role !== undefined) as cfn.PipelineCreateReplaceChangeSetAction;

```

**Comment by RomainMuller** [comment]
Yeah, I'm going to be exporting some of the elements you need in order to make this workable (access to the underlying `PipelineCreateReplaceChangeSetAction` role, as well as ability to submit props for `capabilities`, `role` and `fullPermissions` (similar behavior as those of the CloudFormation CodePIpeline actions).

With respects to the template parameters, it is a little trickier as I intend to be using the templateConfiguration to wire in the assets data... It's not clear to me whether you have a clear use-case for using `templateConfiguration` or `parameterOverrides` just yet or if this is hypothetical... We can track/expedite those in a separate issue if there is a use-case.

**Comment by RomainMuller** [comment]
@moofish32 the `capabilities` being exposed/settable makes a lot of sense anyway.

**Comment by RomainMuller** [comment]
We need to give the example in the `README.md` the literate treatment (hopefully it doesn't imply creating circular dependencies...) so we can maintain guarantee that it at least compiles. I'll get to this once #1165 has landed.
