### ISSUE TITLE
DynamoDB Support for BillingMode

### ISSUE THREAD

**Issue by mikecann** [awslabs/aws-cdk#1313]
DynamoDB now supports billing modes for on-demand pricing (yey 😄 )

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BillingModeSummary.html

Would be awesome if we could get it included in `@aws-cdk/aws-dynamodb`, I could have a stab at doing a PR but im not sure if you guys dont just have an automatic API builder or something?

**Comment by mikecann** [comment]
Hmm the plot thickens, it seems like "billingMode" is available according to the docs: https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-dynamodb.html#@aws-cdk/aws-dynamodb.cloudformation.TableResourceProps.billingMode

But I cant work out how you are supposed to access / set it (Typescript v 0.19.0)

**Comment by rix0rrr** [comment]
What you're seeing is that the billing mode is available at the (autogenerated) L1 level, but not yet at the (hand-written) L2 level, with a nice shiny API.

We'll happily accept a patch if you feel like making one. Otherwise, I suggest you [add overrides at the lower level](https://awslabs.github.io/aws-cdk/aws-construct-lib.html#access-the-aws-cloudformation-layer) to unblock yourself we have support at a higher level.
