### ISSUE TITLE
LogGroup#extractMetric doesn't support '/' character or tokens/derived metric namespace or names.

### ISSUE THREAD

**Issue by sam-goodwin** [awslabs/aws-cdk#1351]
[LogGroup.extractMetric](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-logs.html?highlight=metricfilter#metric-filters) includes the metric namespace and name in the underlying construct name. This prohibits valid namespaces such as those that contain a `/`, or any derived token values such as function names etc.

```typescript
const myFunc = new lambda.Function(..)
logGroup.extractMetric('$.myMetric', `mynamespace${myFunc.functionName}`, 'mymetric');
```

Throws error:

```
Error: Construct names cannot include '/': mynamespace/${Token[MyFunction.Ref.13]}_mymetric
```

**Comment by eladb** [comment]
Interesting. there's an attempt of extractMetric to use the namespace as a construct name, but if the name includes a token, this whole idea kind of fails.

**Comment by rix0rrr** [comment]
I expected the namespace to be static while writing this, like `MyApp`.

**Comment by rix0rrr** [comment]
Agreed on both of those.

**Comment by eladb** [comment]
What I ended up doing is basically allow "/"s to be included in construct IDs, but they are mangled to "--" as soon as the construct is created. I think in most cases that won't be horribly surprising or problematic because it's quite rare for people to actually want to find constructs by their ID. In the rare case, I've added some documentation to that effect.
