### ISSUE TITLE
Impossible to use pseudo-parameters in CFN Mapping

### ISSUE THREAD

**Issue by rsmogura** [awslabs/aws-cdk#1363]
Hi CDK team,

I recently tried to use following construct to get mapping parameter basing on account and region
```
let mappings = new cdk.Mapping(this, 'RegionsMap', {
            mapping: {
                "us-west-2": {
                    "000000000000": "..."
                }
            }
        });

mappings.findInMap(new cdk.AwsRegion(), new cdk.AwsAccountId());
```
However during execution I get exception (https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/cloudformation/mapping.ts#L36) as `findInMap` tries to check if value is in map.

I wonder if mentioned check could be removed, as syntax with `findInMap` is shorter and less error prone than `new cdk.FnFindInMap`.

**Comment by eladb** [comment]
Makes sense of course. We could use `cdk.unresolved` to determine if the key is a concrete string or a token like `{AWS::Region}` and only check existence of the key if it's resolved

**Comment by secpaul** [comment]
The fix for this assumes that the two parameters are either string or pseudo parameters. If the first is a  pseudo parameter and the second a static string it fails with:
TypeError: Cannot use 'in' operator to search for 'ami-id' in undefined

This is due to a dependency on the first parameter resolving when checking the second.

The fix is:

33c33
<         if (!token_1.Token.unresolved(key2) && !(key2 in this.mapping[key1])) {
---
>         if (!token_1.Token.unresolved(key1) && !token_1.Token.unresolved(key2) && !(key2 in this.mapping[key1])) {
