### ISSUE TITLE
VpcNetwork - maxAZs default value exceeds default EIP limit

### ISSUE THREAD

**Issue by shimzim** [awslabs/aws-cdk#1460]
When synthesizing a VpcNetwork construct with default values, it creates a NAT with an EIP per-AZ. Some regions (such as us-east-1) have 6 AZs, while the default EIP limit is 5.

This can be addressed in various ways:
- Reduce the maxAZs default to 3.
- Allow a setting of "unlimited" for maxAZs
- Add specific examples with maxAZs here: https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-ec2.html

Or other solutions :)

Thanks!

**Comment by eladb** [comment]
@leepa could you advise please?

**Comment by PaulMaddox** [comment]
Default maxAZs == 3 seems a sane default. It gives a good trade off between availability / cost, works for applications that need an odd number of AZs for consensus protocols (raft etc), and solves this issue. That gets my vote.

**Comment by rix0rrr** [comment]
Sure. Also this will be a breaking change to VPCs currently deployed to `us-east-1`.

**Comment by leepa** [comment]
If account has access to Trusted Advisor API then we can build context in advance of a run? That'd be a nice touch - stops someone running a stack that uses more of a resource then there is available.

I have some concerns about bringing in defaults. Partly because of breaking changes but also that which AZs do you pick? The first three, the middle three, the last three? I guess there's no real right answer here and no approach is clean. That said:

1. Having a default of 'Quorum' (3) seems like a sane start. Then an option for 'Max' (all in a region).
2. It'd be nice to use NAT instances instead of Gateways - look up the latest NAT Instance AMI and let that be used. It doesn't need EIPs and great for development environments accordingly.

If there's some way to do that as a global thing within the stack's context then we could make it not break by checking the context of how many AZs are currently there? Not sure how that might work in the real world but a thought regardless.

**Comment by rix0rrr** [comment]
> Which AZs do you pick?

I think the easiest and not-incorrect answer is "the first three". I'm not sure that I agree it's "not right"; this is exactly why EC2 does implicit AZ shuffling, so that you can just pick the first three. Anything else would only be required if you plan to create 2 VPCs in the same account, which I don't suppose is going to be a common use case.

> It'd be nice to have the option to use NAT instances instead of Gateways

Feature requested here previously: https://github.com/awslabs/aws-cdk/issues/1305

> If there's some way to do that as a global thing within the stack's context then we could make it not break by checking the context of how many AZs are currently there

Good point; if your stack has already been deployed and you've checked in the `cdk.json`, this is actually already done; the list of AZs will have been stored in there, so it actually won't break existing deployments.

**Comment by leepa** [comment]
> Anything else would only be required if you plan to create 2 VPCs in the same account, which I don't suppose is going to be a common use case.

It's common in production accounts. It's actually part of some standard patterns and quick starts that are published as well.

**Comment by shimzim** [comment]
The whole beauty of VPC is that it allows you to create multiple isolated
environments in a single account. AFAIK it's a common usecase.

**Comment by rix0rrr** [comment]
I was under the impression the current recommendation is to use multiple account, but I'll yield to those with more experience.

However, I think there are two different discussions to be had here:

* Reduce the number of AZs selected by default: we're all in favor of doing this. Does not materially reduce the functionality of the VPC construct, since right we don't allow selective AZ picking anyway.
* Being selective about AZs picket: [already has a ticket, please move discussion of this topic there](https://github.com/awslabs/aws-cdk/issues/1037)

**Comment by eladb** [comment]
Is it safe to say we all agree that setting maxAzs to 3 is a good path forward for this?

**Comment by rix0rrr** [comment]
Fixed by https://github.com/awslabs/aws-cdk/pull/1543
