### ISSUE TITLE
export() must be idempotent (was: error when calling export() on multiple items)

### ISSUE THREAD

**Issue by BDQ** [awslabs/aws-cdk#1496]
The Stack code below results in the following error:

>  Error: There is already a Construct with name 'PublicSubnetIDs' in VpcNetwork

```javascript
export class ClusterStack extends cdk.Stack {
  public readonly vpcRefProps: ec2.VpcNetworkRefProps;
  public readonly ecsClusterRefProps: ecs.ImportedClusterProps;

  constructor(parent: cdk.App, name: string) {
    super(parent, name);

    // VPC using a small CIDR for staging
    const vpc = new ec2.VpcNetwork(this, "vpc", {
      cidr: "10.0.0.0/24",
      maxAZs: 2
    });

    // Create the ECS cluster
    const cluster = new ecs.Cluster(this, "cluster", {
      vpc
    });

    // export vpc
    this.vpcRefProps = vpc.export();
    // export cluster
    this.ecsClusterRefProps = cluster.export();
  }
}
```

**Comment by rix0rrr** [comment]
Related to:

https://github.com/awslabs/aws-cdk/issues/1095
https://github.com/awslabs/aws-cdk/issues/89 (indirectly)

**Comment by eladb** [comment]
The issue here is `vpc.export()` is called twice: once explicitly in the code and then implicitly as a result of `cluster.export()`. And our current pattern for implementing those exports is that we always define a set of `new cdk.Output`s for each attribute that we wish to export.

Naturally these outputs can be reused if they are already defined.

Since this is implemented across our entire library, we can probably use some sugar methods so that implementing exports will not be a pain everywhere.

I'll rename the issue to reflect this requirement.

**Comment by rix0rrr** [comment]
export() no longer exists.
