### ISSUE TITLE
CDK diff/deploy throws "Bad Gateway" when using --profile option

### ISSUE THREAD

**Issue by pedrobento988** [awslabs/aws-cdk#1598]
Hello,

I'm attempting to deploy/diff a new stack with --profile option through CDK, but I'm getting the error:
Bad Gateway
502: Bad Gateway

Currently my ~/.aws/credentials file has the following structure:
[default]
aws_access_key_id="value1"
aws_secret_access_key="value2"
aws_session_token="value3"
[154]
aws_access_key_id="value1"
aws_secret_access_key="value2"
aws_session_token="value3"

Both profiles have the same AWS keys.

File ~/.aws/config file has the following contents:
[default]
region=eu-west-1
output = json
[154]
region=eu-west-1
output = json

If I type "cdk diff", it works.
If I type "cdk --profile 154 diff" / "cdk diff --profile 154", it doesn't work and throws the mentioned error.
In 'attachment' I send you the error output with "-v" option: [cdk_bad_gateway_error.txt](https://github.com/awslabs/aws-cdk/files/2787644/cdk_bad_gateway_error.txt)

I'm using CDK with Java and Windows 10.

I did not try other languages or OS.

AWS CLI works with both ways: "aws s3 ls" or "aws s3 ls --profile 154" .

**Comment by rix0rrr** [comment]
I believe `~/.aws/config` has to look like this:

```
[default]
region=eu-west-1
output = json
[profile 154]
region=eu-west-1
output = json
```

Notice the `profile` I added. 

I think it happens to work for you in the AWS CLI because it will fail to find `profile 154` and then fall back to using the settings from `default`, which happen to be the same settings as those from `154`.

The AWS SDK for JavaScript does NOT fall back to the `default` profile for settings, and so when it fails to find `profile 154` it will not know what region you want to connect to.

**Comment by pedrobento988** [comment]
Yes, you are right. For future reference, the named profile specifications are documented here:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

Never realized that since that since AWS CLI has that fallback mechanism.
Thanks for help!
