### ISSUE TITLE
Explain "synthesis time" and "deploy time"

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1790]
See: https://github.com/awslabs/aws-cdk/issues/1782

**Comment by Doug-AWS** [comment]
I take it there are three possible solutions:

- Wrap 'cdk deploy' in a shell script
- Use a custom resource
- Use code pipeline and code deploy

Do we want to describe all three? Order the list from best/recommended to worst/least recommended?

**Comment by eladb** [comment]
I am failing to understand how  #1782 is related. Seems like a confusion here between custom resources and lifecycle events

**Comment by Doug-AWS** [comment]
1782 is related because Rico told me it was:

We need some explanation of "synthesis time" and "deploy time" in the docs under the concepts section.

I'm seeing this pop up on GitHub and I need to be able to point them to a doc page, because I can smell confusion from the question: https://github.com/awslabs/aws-cdk/issues/1782
...

**Comment by rix0rrr** [comment]
I would have liked a doc page that explains the lifecycle so that I could have pointed them to it and tell them "it cannot exist." (today)

**Comment by Doug-AWS** [comment]
I'll add lifecycle info to the "Writing Constructs" section and amend the description of 'cdk deploy' in the hello world tutorial, which is the first place we talk about 'cdk deploy'. Once I've rebuilt the docs to the public site, I'll add links to those two sections here, and close this issue.

**Comment by Doug-AWS** [comment]
Here's the proposed outline for the lifecycle info:

Lifecycle
        (each one deserves at least a paragraph if not a topic)
        [CLI] "resolve" (context from environment)
        [APP] "define" (initializes the tree)
        [APP] "validate" (calls "validate")
        [APP] "prepare" (pre-synthesis preparations)
        [APP] "synthesize" (emit artifacts such as templates and assets)
        [CLI] "build" (produces a "cloud assembly" from the app synthesized output)
        [CLI] "deploy" (upload assets, provision resources, in-order of dependency between stacks)

Who wants to volunteer to provide the first draft? Or do we have something written down somewhere that I can crib?

**Comment by rix0rrr** [comment]
# Life cycle of a CDK application

```
                                                                                                               
                         Running your CDK app                                             CloudFormation       
               ◀──────────────────────────────────────────▶                         ◀─────────────────────────▶
                                                                                                               
              ╔═══════════╦═════════╦══════════╦═══════════╗                       ╔══════════════════════════╗
 cdk app      ║           │         │          │           ║       template        ║                          ║
 source  ────▶║ Construct │ Prepare │ Validate │ Synthesis ║─────▶ and other ─────▶║        Deployment        ║
  code        ║           │         │          │           ║       artifacts       ║                          ║
              ╚═══════════╩═════════╩══════════╩═══════════╝                       ╚══════════════════════════╝
                               ▲                                                                 ▲             
                               │                                                                 │             
                               │ Toolkit calls                                     ...then sends │             
                               │ your app...                                           output to │             
                               │                                                  CloudFormation │             
                               │                                                                 │             
                ┌─────────────────────────────────────────────────────────────────────────────────────────────┐
                │                                                                                             │
                │                                           Toolkit                                           │
                │                                                                                             │
                └─────────────────────────────────────────────────────────────────────────────────────────────┘
```

There are three actors at play to deploy your CDK-based application.

* Your **CDK app**, which describes your cloud application.
* **CloudFormation**, which is ultimately going to deploy your application
  and create all AWS resources your app describes.
* The **CDK toolkit**, which ties the two together.

After you use the toolkit to deploy a CDK application, the application goes through the following phases:

* **Construction**: this is where your code instantiates all desired application constructs and links them together.
* **Preparation**: all constructs that have implemented their `prepare()` method participate in a final round of
  modifications, to set up any final state they want to. The preparation phase happens automatically and users don't
  have to worry about this.
* **Validation**: all constructs that have implemented their `validate()` method can validate themselves
  to make sure they've ended up in a state that will correctly deploy later on. Users will see any validation failures
  that are detected during this phase.
* **Synthesis**: all constructs render themselves to a set of artifacts, representing CloudFormation templates, 
  AWS Lambda application bundles, and other deployment artifacts. Users do not have to worry about this phase.
* **Deployment**: the toolkit will take the set of artifacts produced by the synthesis step, upload them to S3
  or wherever they need to go, and finally start a CloudFormation deployment that will deploy the application. 

## Important take-aways

Please take note that your CDK app has already finished its job and exited by the time the CloudFormation deployment
starts. This has a couple of implications:

* Your CDK app cannot respond to events that happen during deployment (for example, a resource being created
  or the whole deployment finishing). If you wish to run any code during the deployment phase, you will have
  to inject it into the CloudFormation template as a Custom Resource.
* Your CDK app might have to work with values that cannot be known at the time it executes. For example, if your
  CDK application defines an S3 Bucket with an automatically generated name, and you retrieve the `bucket.bucketName`
  attribute, what that name will be after it has been deployed cannot be known yet. Instead, the value of
  the `bucketName` attribute will be a *symbolic* value, looking somewhat like `"${TOKEN[Bucket.Name.1234]}"`.
  You can pass this value to constructs, or append it to other strings, and the CDK framework will make sure
  to translate these values to the right pieces of CloudFormation teplate. The only thing you *cannot* do is look
  at the value and make decisions based on the *actual* bucket name, because the bucket name will only be known
  later on once CloudFormation is done deploying, and by that time your program will not be running anymore.
  To figure out if you have one of those "unresolved" values, you can call `cdk.unresolved(value)` which
  will return `true` if the value will only be known at deployment time.

**Comment by rix0rrr** [comment]
@Doug-AWS my take.

I find the diagram VERY important for understandability. I can understand you might not want to include this ASCII diagram that I drew here, but please do find a way to replace it with a graphical one then.

**Comment by Doug-AWS** [comment]
Awesome Rico. I'll crank out a Visio->PNG and add a new topic to the guide by EOW.

**Comment by Doug-AWS** [comment]
![lifecycle](https://user-images.githubusercontent.com/16107690/53573914-64a5ea80-3b23-11e9-9720-e5cc79d49b04.png)

**Comment by rix0rrr** [comment]
There's a few too many boxes here for my taste which make it too hard to see what's going on. I do like something else you've done, which is show both "cdk deploy" and "cdk synth".

So something like:

* You added an arrow to say "...creates CloudFormation..". That's actually not what happens. Please remove it.
* The box that says "Synthesis (cdk synth)", make that say "CDK app".
* If you're in Visio anyway, I meant the arrow line that says "CDK app" to be a line that's usually used to indicate length, so like `|------ CDK app ------|`, but my drawing program only had arrows. But how about we use THAT to indicate operation spans. So make it look like this (not on my computer that has the fancy ASCII art program now so excuse the shitty diagram):


```
| - - - - - - - - - - -- cdk deploy -- -- - - - - - -- - - --|

|- - - - cdk synth - - - - - - - - -|

+------------- CDK App -------------+
|                                   |
| Consruct -> Prepare -> Validate.. |
|                                   |
+-----------------------------------+
```

* Don't really like the dashed outlines, especially not around the "Deploy" box. Now, I understand you did that to make the boxes on the left, inside the other box, stand out. I think we can achieve the same but have it better glanceable by shading them in light grey.
* If you *really* want to outline the "app source" and "template and other artifacts" boxes, put the dashed outlines there please. Those `[| box |]` outlines are distracting to me.
* Please make the artifact boxes and the processing boxes the same height. The artifact boxes are higher now, it looks jumbly.
* Please make the arrows go all the way to the "Synthesis" (to be renamed "CDK app") and "Deploy" boxes. Those things aren't input into a "deploy" process, they're inputs to the app and to cloudformation.
* I guess we'd have to mirror an outer box labeled "CloudFormation" around the "deploy" phase.
* Please restrict the number of font sizes to 2. I think most box labels are the same size (good), the labels next to the arrows are smaller (fantastic), but then the "CDK Toolkit" label is a bigger font size. The more font sizes there are, the more visually disorganized something looks.

**Comment by Doug-AWS** [comment]
Okay, here's the latest:

![lifecycle](https://user-images.githubusercontent.com/16107690/53589502-6af88e80-3b44-11e9-887e-205712e71122.png)

**Comment by rix0rrr** [comment]
In my mind I was thinking something like this (but then please non-ugly, I threw this together with OpenOffice):

![image](https://user-images.githubusercontent.com/524162/53627812-b759d200-3c09-11e9-9c96-6b3009895a39.png)

I would like to keep the definition around the phase blocks (right now they're just words floating in empty space).

I know what you're doing with the monotype font for the `cdk synth` and `cdk deploy` commands, but it looks a little ugly and confusing to me.

And these are the "dimension lines" I was thinking of to demarcate a time interval.

**Comment by rix0rrr** [comment]
I was just considering: what if we put the Toolkit at the top, use quotes "" to indicate it's the "cdk" command (to replace the teletype font). Or maybe we combine a color with the teletype font to indicate it's a command you type?

And then we put the timelines at the bottom. Maybe this makes more sense since it draws your eye first to the toolkit (which is the first thing you'll invoke) and we'll introduce the timeline and link it to the command only *after* we've introduced the command.

Another pass with the reverse:

![image](https://user-images.githubusercontent.com/524162/53628207-b4abac80-3c0a-11e9-9b8b-e657063c924e.png)

**Comment by rix0rrr** [comment]
An attempt with colorization combined with monotype to draw attention to shell commands:

![image](https://user-images.githubusercontent.com/524162/53628312-048a7380-3c0b-11e9-9aee-b03ef4de6ef6.png)

**Comment by rix0rrr** [comment]
By the way, here's my "one golden rule of aesthetics" that I'm living all my visual design feedback by (and that I use for shape choices, font choices, color choices, even the clothes I wear):

## Things should be either *exactly* the same or *obviously* different

That means:

* Objects are either the same size, and line up on a line, or they're *obviously* in a different location or of a different size.
* Fonts are either exactly the same, or *obviously* different (something that's the same size and color but a slightly different font, like the monotype, just looks a little off)
* etc.

**Comment by Doug-AWS** [comment]
Here's a version that combines the "CDK Toolkit" block with the two CDK commands, synth and deploy. It just looks odd that they are above and below the lifecycle steps, when they are more closely related. I also made the commands bold, as in **cdk synth** and **cdk deploy**:

![lifecycle](https://user-images.githubusercontent.com/16107690/53641146-ec9ef980-3be2-11e9-9d01-ff989c19806d.png)

**Comment by rix0rrr** [comment]
I find this confusing too. The "CDK toolkit" block indicates a physical component while the "cdk synth" and "cdk deploy" lines indicate timelines.

Because they represent a (time) range/interval, I prefer the dimension lines (T caps as opposed to dots).

I know that my artifacts blocks had dots, but I actually preferred your dashes from the first diagram you sent. It's just that OpenOffice didn't have the dashes I wanted.

You lost alignment on the dashed boxes (w.r.t. the phase boxes) again.

If it's at all in the cards, I would prefer the "...then sends output" block to have left-aligned text, so the left hand side of the text forms a nice parallel edge to the line.

I should have stated this more clearly, but I actually preferred when you had the "CDK app" and "CloudFOrmation" captions directly on the boxes' borders. It's just that my OpenOffice drawing program did not allow me to do the same in my example drawing.

**Comment by Doug-AWS** [comment]
Visio does not have a vertical bar for a line endpoint, so I'm using what they give me:

![lifecycle](https://user-images.githubusercontent.com/16107690/53644093-91710500-3bea-11e9-9658-17cf9af286f2.png)

**Comment by Doug-AWS** [comment]
I'm wondering if it's more confusing to include the cdk commands in the diagram. What if we changed "CDK Toolkit" to "CDK Toolkit (**cdk deploy**)" and removed both commands:

![lifecycle2](https://user-images.githubusercontent.com/16107690/53644535-ab5f1780-3beb-11e9-9036-fe5f701ada14.png)

**Comment by rix0rrr** [comment]
Let's do that then. It's probably a fine compromise.

**Comment by rix0rrr** [comment]
I'm happy with the last one! Maaayyyybe we could get a slightly lighter shade of grey, but otherwise, ship it!

**Comment by Doug-AWS** [comment]
5% fill it is:


![lifecycle2](https://user-images.githubusercontent.com/16107690/53645583-042faf80-3bee-11e9-8252-8678104c4c8d.png)

**Comment by Doug-AWS** [comment]
Final (hahahaha) URL: https://docs.aws.amazon.com/cdk/latest/guide/lifecycle.html

**Comment by frankoid** [comment]
https://docs.aws.amazon.com/cdk/latest/guide/lifecycle.html now redirects me to https://docs.aws.amazon.com/cdk/v2/guide/home.html

The latest URL seems to be https://docs.aws.amazon.com/cdk/v2/guide/apps.html#lifecycle (the above diagram is there)
