### ISSUE TITLE
Docs: Add info on what "cdk bootstrap" creates.

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1812]
- Is the user on the hook for any costs? 
- What do we create for them? 
- Do we have a list? 
- If they decide to no longer use the CDK, how do they delete these resources?

**Comment by rix0rrr** [comment]
Do you need this info, or are these notes for yourself?

**Comment by Doug-AWS** [comment]
I need the info, hence the "needs contributors" label.

**Comment by rix0rrr** [comment]
Here's what we create:

https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap-environment.ts#L14

Today it's a Bucket. They pay for what's in there. We don't clean it currently, so it accumulates.

In the future, we'll probably add ECR repositories. They will pay for what's in there as well.

In the future, we'll probably add a Lambda function that executes on a schedule. They will pay for the executions, but the Lambda function's gonna clean up unused resources, so that should save them some money.

They get rid of it by deleting the `CDKToolkit` stack from their account.

**Comment by Doug-AWS** [comment]
Thanks. I'll create a draft soon and send it out for review.

**Comment by Doug-AWS** [comment]
Here's what I have so far:

## Bootstrapping the CDK

Before you can use the CDK you must bootstrap the CDK to create the infrastructure that the CDK needs. Currently the bootstrap command creates only an Amazon S3 bucket.

You incur any charges for what the CDK stores in the bucket. Because the CDK does not remove any objects from the bucket, the bucket can accumulate objects as you use the CDK. You can get rid of the bucket by deleting the *CDKToolkit* stack from your account.

**Comment by rix0rrr** [comment]
Yep, good for now.

**Comment by rix0rrr** [comment]
The part about it that I don't like is that it will just invite more questions. But I guess those are the ways.

**Comment by Doug-AWS** [comment]
Yep, opening Pandora's box.

**Comment by Doug-AWS** [comment]
See https://docs.aws.amazon.com/CDK/latest/userguide/tools.html#tools_bootstrap

**Comment by Dzhuneyt** [comment]
What about adding a `cdk bootstrap --destroy` possibility (https://github.com/aws/aws-cdk/issues/986#issuecomment-432178288)? I think it would be much more intuitive than having to delete the CloudFormation stack from the AWS console.
