### ISSUE TITLE
When will cdk eill be made available for production use cases

### ISSUE THREAD

**Issue by YiannisH** [awslabs/aws-cdk#2022]
Anyone here knows if aws has a roadmap for when it will reach a stable version and will be suitable for production use cases?

**Comment by rix0rrr** [comment]
We generally don’t share specific dates for unreleased products, but are aiming for Q3 this year to launch CDK GA. We are in the process of running usability studies to identify rough edges and scoping end-to-end use cases so that we have confidence in a product that will meet our customer’s expectations for high quality and a delightful developer experience.
