### ISSUE TITLE
Get rid of aws-codedeploy-api and asCodeDeployLoadBalancer

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#2449]
I don't see a problem for the aws-codedeploy module to take a dependency on aws-elbv2 and aws-elb, eliminating the need for this intricate type hierarchy.

**Comment by skinny85** [comment]
A little bit of an explanation why it was modeled this way.

We wanted to pass either a Classic ELB, or an ALB/NLB Target Group directly to the `loadBalancer` property of a CodeDeploy Deployment Group when creating it:

```ts
new codedeploy.DeploymentGroup(this, 'DG', {
  // ...
  loadBalancer: new elasticloadbalancing.LoadBalancer(this, 'ELB', {
    // ...
  }),
});
```

Because CodeDeploy depends on `aws-autoscaling` (for `AutoScalingGroup`), it has a transitive dependency on both `aws-elasticloadbalancing` and `aws-elasticloadbalancingv2`, and so none of those packages could have a type from `aws-codedeploy` that could be implemented by both `elasticloadbalancing.LoadBalancer` and `elasticloadbalancingv2.TargetGroup` (as that would be a cycle).

If you want to get rid of this dependency, we need to change the current API of `DeploymentGroup`.

**Comment by eladb** [comment]
Yes, let's change the API.

Would it make sense to use "union-like classes":

```ts
loadBalancer: codedeploy.LoadBalancer.classic(elb)
// or
loadBalancer: codedeploy.LoadBalancer.targetGroup(group)
```

**Comment by skinny85** [comment]
Yeah, that's probably the only sensible way to go here.
