### ISSUE TITLE
CodeBuild: Missing the latest aws/codebuild/standard:2.0 Docker image

### ISSUE THREAD

**Issue by digitalsanctum** [awslabs/aws-cdk#2606]
**Describe the bug**
The `LinuxBuildImage` class is missing `UBUNTU_18_04_STANDARD_2_0`

**Expected behavior**
CDK should include all the standard Docker images provided by CodeBuild as listed here: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

**Version:**
 - Ubuntu 18.04
 - Kotlin with Java CDK artfifacts
 - 0.31.0

**Comment by skinny85** [comment]
Hey @digitalsanctum ,

the standard image instances have been renamed to `LinuxBuildImage.STANDARD_1_0` and `STANDARD_2_0`in #2541 . The reason is that they're no longer tied to the Ubuntu 18.04 platform (the platform might change with time, for example to the next Ubuntu LTS release), hence the name change.

Hope this clears this up, let me know if not.

**Comment by digitalsanctum** [comment]
@skinny85 Thanks for clarification. I just need to wait for the next release then. In the meantime, I'm using the following: `LinuxBuildImage.fromDockerHub("aws/codebuild/standard:2.0")`

**Comment by knorms101** [comment]
@skinny85  Users cannot choose the latest CodeBuild images until a new static constant is added to `LinuxBuildImages` and the user updates to the latest version of cdk.  Users may want the latest images, but be unable to update due to some breaking cdk change.

The work-around that @digitalsanctum proposed for using the latest aws CodeBuild image, `.fromDockerHub` is no longer available. Would it be possible to expose a different work-around? I notice in [aws-codebuild/lib/project.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1231) all the static CodeBuild images are created using a private `codebuildImage` method. Could this method be exposed so users could specify the latest image?

**Comment by skinny85** [comment]
@knorms101 that is an excellent point. Would you be willing to whip up a quick PR fixing this problem, and adding the appropriate documentation to the CodeBuild's project ReadMe?

**Comment by knorms101** [comment]
@skinny85 Absolutely! Thanks.
