### ISSUE TITLE
Add an `addToPipeline` method for L2 Constructs like CodeCommit Repositories and CodeBuild Projects

### ISSUE THREAD

**Issue by skinny85** [awslabs/aws-cdk#265]
As discussed in the comments of #238 .

**Comment by skinny85** [comment]
Now that #459 has been pushed, we can do this again!

I'm wondering what should the API look like? Here's my first draft, based on CodeCommit Repository:

```ts
const pipeline = new codepipeline.Pipeline(this, 'MyPipeline');
const sourceStage = new codepipeline.Stage(this, 'Source', { pipeline });
const repository = new codecommit.Repository(this, 'MyRepo', {
    repositoryName: 'MyRepo',
});

const sourceAction = repository.useAsSourceInPipeline(sourceStage, {
    artifactName: 'SourceOutput',
    runOrder: 99,
    // other Action-level properties here...
});

// use sourceAction.artifact here as input to subsequent Actions...
```

Does this make sense?

**Comment by eladb** [comment]
Here are some ideas @skinny85 and I have been talking about:

```ts
const repository = new codecommit.Repository(this, 'MyRepo', {
    repositoryName: 'MyRepo',
});

const pipeline = new codepipeline.Pipeline(this, 'MyPipeline');

const stage = pipeline.addStage('Source');
stage.addSourceAction(repository, { actionName: 'MySource', runOrder: 99 });
stage.addBuildAction(

class Repository implements IPipelineSource {
    /** use stage.addSourceAction(repo) **/
    public asPipelineSource(pipeline: Pipeline, name?: string) {
        new RepositoryCodePipelineSourceAction(this, 'Source', { pipeline });
    }
}
```

**Comment by RomainMuller** [comment]
So the `stage.addSourceAction` is going to be awkward if it needs to pass props down to the `IPipelineSource#asPipelineSource`, since those will not always the the same type. Making it type-safe would involve using a convoluted generic declaration, which `jsii` wouldn't be able to process currently.

A first step would be to reverse the direction and have:
```ts
// In @aws-cdk/aws-s3
export class Bucket /*...*/ {
    /*...*/
    public addToPipelineStage(stage: codepipeline.Stage, id: string, props: { path: string }) {
        new S3CodePipelineSourceAction(this, id, { ...props, stage });
    }
}
```

This solves the problem of the props type being heterogenous, and makes discoverability of pipeline actions from the providers more straight-forward. Also helps hiding the long class names for the `PipelineAction` classes.

If/when jsii supports generics, we can make the action providers implement (obviously can also have specialized `IPipelineSourceActionProvider<Props>` and whatnot):
```ts
export interface IPipelineActionProvider<Props> {
    addToPipelineStage(stage: codepipeline.Stage, name: string, props: Props): codepipeline.Action;
}
```

And then provide a Stage method such as, in order to allow development workflows that start with the pipeline and work from there:
```ts
export class Stage /*...*/ {
    /*...*/
    public addSourceAction<Props>(provider: IPipelineActionProvider<Props>, name: string, props: Props) {
        return provider.addToPipelineStage(this, name, props);
    }
}
```

**Comment by skinny85** [comment]
First (of probably many) PR: #616

**Comment by skinny85** [comment]
Second PR: #642

**Comment by skinny85** [comment]
Third PR: #647

**Comment by skinny85** [comment]
I'm resolving this one, as all 3 PRs have been merged.
