### ISSUE TITLE
Please add an option to specify the template format (YAML or JSON) in cdk sdk

### ISSUE THREAD

**Issue by amitsha** [awslabs/aws-cdk#722]
We're using the aws-cdk sdk to generate templates using `stack.toCloudformation()` method. The default template format is JSON, which isn't the preferred format for our team.

It would be nice if you could provide an option to specify the template format or change the default format to `YAML` instead of `JSON`.

**Comment by rix0rrr** [comment]
The output of `stack.toCloudFormation()` is nested JavaScript structures: objects, lists and strings.

You are free to convert these to JSON by calling `JSON.stringify()`, or to YAML by using a yaml generating library like [yaml-js](https://www.npmjs.com/package/yaml-js).

If you synthesize using the [`aws-cdk` toolkit](https://awslabs.github.io/aws-cdk/tools.html#command-line-toolkit-cdk) (which we recommend you do unless you have a really good reason to do otherwise) the default output will be YAML unless you pass `--json`.

**Comment by eladb** [comment]
In general, `toCloudFormation` is "not the whole story". For example, if you use [environment context](https://awslabs.github.io/aws-cdk/context.html) such as the `AvailabilityZoneProvider`, your template will contain dummy values instead of the actual set of AZs in your environment.

Ideally, you should use `cdk synth` to synthesize your templates, but we realize there might be some use cases where you'd want to invoke this from your code (and not through the command line). We are considering vending the toolkit as a library for these purposes. Can you elaborate on your use case so we'll be able to take your use case into account?
