### ISSUE TITLE
Consider making Construct stack-aware

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#798]
We are starting to realize that the fact the `Construct` is not stack-aware hinders our ability to provide a good experience. For example, to get a handle to the stack, users need to write `Stack.find(this)` instead of something like `this.stack`. Similarly, if I want to find a resource, I can use `this.findChild` but have to cast it down to `cdk.Resource`. Would have been handy to have `this.findResource`, etc.

A possible simple solution to this is to convert the base `Construct` to `BaseConstruct` and then define a new class `Construct` which will be `Stack` and `Resource` aware and will have the desired APIs.

Brought up by @ccurrie-amzn in a [discussion](https://github.com/awslabs/aws-cdk/pull/784#discussion_r220727340) over #784

**Comment by rix0rrr** [comment]
I would have loved to have something like this before, but I was under the impression the rationale for not having it was to avoid tying ourselves to CloudFormation concepts.

**Comment by eladb** [comment]
That’s correct, the question is whether we define a Stack as a CloudFormation concept or a more general one.

**Comment by rix0rrr** [comment]
As an implementation note, `StackElement` already has a `stack` property.

**Comment by RomainMuller** [comment]
I think making `stack` visible on the `.nodes` property does not create a strong decision on whether `Stack` is a CloudFormation or CDK concept. Indeed, it pertains to the top-level `Stack` class, which we can still have mean anything we'd like, and it could synthesize into a CloudFormation stack AND some not-CloudFormation things.

Anyhow - I'm adding those couple of convenience accessors, because I'm real tired of `Stack.find(this).formatArn({ ...});`
