### ISSUE TITLE
.NET generation needs to use full type names for reused names cross-construct.

### ISSUE THREAD

**Issue by costleya** [awslabs/aws-cdk#802]
Names can be re-used across packages. Full type names need to be used to protect against naming conflicts.

See #786

**Comment by RomainMuller** [comment]
The generated Java code uses fully qualified names for everything... Should the C# generator do the same?

**Comment by mpiroc** [comment]
The C# Generator attempts to detect whether a fully qualified name is necessary. See [`SymbolMap`](https://github.com/awslabs/jsii/blob/master/packages/jsii-dotnet-generator/src/Amazon.JSII.Generator/SymbolMap.cs#L97). I would start there when searching for the root cause.

Also, should this be moved to the `jsii` repo?

**Comment by RomainMuller** [comment]
@mpiroc you're absolutely right - I've created awslabs/jsii#252 to track this. Resolving here.
