### ISSUE TITLE
(aws-lambda): runtime list is incorrect/outdated

### ISSUE THREAD

**Issue by leepa** [awslabs/aws-cdk#947]
Lambda@Edge requires nodejs6.10 or nodejs8.10 runtime property yet there's a NodeJS43Edge in the Runtime enumeration and nothing related to these versions. Also NodeJS810 doesn't appear to support Inlineable, not sure if that's important either.

**Comment by eladb** [comment]
* AFAIK Lambda doesn't allow inlining nodejs 8.10 (which is why it's not tagged as inlinable).
* From the [Lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime) it seems like Lambda@Edge is `nodejs4.3-edge` which is where the enum name comes from.
