### ISSUE TITLE
VPC: Default AZs to 3

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#996]
Right now, the default for the # of AZs is "as many as you can get", which leads to consistent problems in us-east-1 (because it has so many AZs): I can't start a default VPC because I run out of EIPs.

What's worse, code that runs fine in one region fails to start in us-east-1 because of this, which is worse. You think you've tested something, but then it doesn't work.

Since there's diminishing returns of additional AZs after the 3rd, why not default to 3? (But let users raise the number, obviously, if they really want to).

Also, we should probably make it possible to define an offset as well, so that you can have two VPCs spread over all 6 AZs (one a-b-c, the other d-e-f).

**Comment by eladb** [comment]
@mindstorms6 @PaulMaddox what do you guys think?

**Comment by PaulMaddox** [comment]
I agree with diminishing returns for spreading architectures across more than 3 AZs, but i don’t think your suggestion is the right way of achieving this.

If we split the VPC CIDR into three AZs worth of subnets, what happens later if they want to add more AZs? The IP space will be all allocated, and their options would be super limited and likely result in a very disruptive redeployment of their whole application.

I think it’s better to carve the VPC subnets into all available AZs, but maybe have a method that gets public/private subnets for a limited number of AZs, which can be used to deploying the applications.

The downside is NAT gateways would be deployed to all SubnetType.Private subnets (incurring a cost), and I’m open to suggestion on ways to improve that - I just can’t think of a nice API experience right now.

Maybe a boolean flag on a subnet configuration for “enabled”? That way subnets could be in a non-active state, reserved for future use.

**Comment by moofish32** [comment]
So for brevity I think defaulting to 3 is a good idea. Now the how is interesting.

If you try to say spread the subnets across all AZs and pick every nth one, the logic is much more complicated and the user is going to have to understand more options because no matter what you do this algorithm of subnet allocation is inherently public.

I personally think for advanced additions [adding additional vpc associations](https://docs.aws.amazon.com/cli/latest/reference/ec2/associate-vpc-cidr-block.html) should be considered. As an enterprise customer we intentionally allocate medium to small blocks for IPAM considerations (aka you are not going to see a /8 /16 in any of our accounts unless it's experimentation). The second part is we (CDK) do not prevent teams from adding subnets to VPCs using the current L2 construct; do we? So as long as you don't allocate all IP space, you can manually carve up your extra space as you see fit. I think it's fair to expect a user that has saturated IP space to be a knowledgeable user and be able to implement this, but that's my opinion with 0 data to support.

So all this leads me to asking what if we kept what is there today, but default the `maxAZs` to 3 unless you specify more? How bad is our L2 Subnet addition experience? I think this is mostly what @rix0rrr was proposing. 

> The downside is NAT gateways would be deployed to all SubnetType.Private subnets (incurring a cost), and I’m open to suggestion on ways to improve that - I just can’t think of a nice API experience right now.

@PaulMaddox what do you think of the current `natGateways: number, natGatewayPlacement: VpcPlacementStrategy`? The issue is if you want to control exactly which subnets use specific Gateways it's not 100% in your control. Again if you have this type of concern, I tend to expect you to be a power user and able to create a proper L2 based on L1s to meet your extremely high performance use case.

**Comment by rix0rrr** [comment]
Actually don't know if offsetting adds any value; only comes into play if you have 2 vpcs in 1 account, and customers would only care about failure domains, not sharding for capacity.

Although I did get an EKS error that in one AZ there was no more EKS capacity, I would want recourse when that happens

**Comment by moofish32** [comment]
@rix0rrr - is it worth separating this issue?

**Comment by rix0rrr** [comment]
Probably
